# Generated by Django 5.0 on 2024-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания действия'),
        ),
    ]
