# Generated by Django 5.0 on 2024-01-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0002_alter_licence_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания эксплуатации'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='conditions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Условия разрешения/лицензии'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='structural_division',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='waste_collection',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дана окончания ипользования набора'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='for_whom',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Кому передается отход'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='from_whom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='От кого поступил отход'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='quantity_generated',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Объем образования отхода'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Объем поступления отхода'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='quantity_transf',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Объем переданных отходов'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='reas_admis',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Причина поступления отхода'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='reas_transf',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Причина передачи отхода'),
        ),
        migrations.AlterField(
            model_name='waste_receivers',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжеения договора'),
        ),
        migrations.AlterField(
            model_name='waste_types',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания использования'),
        ),
    ]
