# Generated by Django 5.0 on 2024-01-15 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0003_alter_cars_end_date_alter_licence_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_data',
            name='name',
            field=models.CharField(choices=[('Топливо', [('DISEL', 'Дизельное топливо'), ('PET92', 'Бензин АИ-92'), ('PET95', 'Бензин АИ-95'), ('PET98', 'Бензин АИ-98'), ('PET100', 'Бензин АИ-100')]), ('Энергоресурсы', [('EL', 'Электроэнергия'), ('HEAT', 'Теплоэнергия'), ('WAT_S', 'Водоснабжение'), ('WAT_D', 'Водоотведение')]), ('Деятельность', [('SOLD', 'Проданная продукция, единиц')]), ('Выплаты', [('TAX', 'Налог на захоронение'), ('FINE', 'Штрафы ООС')])], max_length=100, verbose_name='Наименование показателя'),
        ),
        migrations.AlterField(
            model_name='passport_data',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='Год д.б. 4-х значным!'), django.core.validators.MaxLengthValidator(limit_value=4, message='Год д.б. 4-х значным!')], verbose_name='Год данных'),
        ),
    ]
