# Generated by Django 5.0 on 2024-01-15 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0004_alter_passport_data_name_alter_passport_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danger_class',
            name='code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!'), django.core.validators.MaxLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!'), django.core.validators.MinValueValidator(limit_value=0, message='Код д.б. 2-ух значным!')], verbose_name='Код класса опасности'),
        ),
        migrations.AlterField(
            model_name='passport_data',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='Год д.б. 4-х значным!'), django.core.validators.MaxLengthValidator(limit_value=4, message='Год д.б. 4-х значным!'), django.core.validators.MinValueValidator(limit_value=2017, message='Год д.б. 4-х значным!')], verbose_name='Год данных'),
        ),
        migrations.AlterField(
            model_name='reason_for_transferring',
            name='code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!'), django.core.validators.MaxLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!'), django.core.validators.MinValueValidator(limit_value=0, message='Код д.б. 2-ух значным!')], verbose_name='Код причины'),
        ),
        migrations.AlterField(
            model_name='waste_types',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=7, message='Код д.б. 7-ми значным!'), django.core.validators.MaxLengthValidator(limit_value=7, message='Код д.б. 7-ми значным!'), django.core.validators.MinValueValidator(limit_value=0, message='Код д.б. 7-ми значным!')], verbose_name='Код отхода'),
        ),
    ]
