# Generated by Django 5.0 on 2024-01-15 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0005_alter_danger_class_code_alter_passport_data_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_data',
            name='year',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='Год д.б. 4-х значным!'), django.core.validators.MaxLengthValidator(limit_value=4, message='Год д.б. 4-х значным!'), django.core.validators.MinValueValidator(limit_value=2017, message='Год д.б. 4-х значным!')], verbose_name='Год данных'),
        ),
    ]
