# Generated by Django 5.0 on 2024-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0008_alter_passport_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_types',
            name='picture',
            field=models.ImageField(upload_to='ecology/templates/ecology/images/waste_image/', verbose_name='Картинка отхода'),
        ),
    ]
