# Generated by Django 5.0 on 2024-01-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0009_alter_waste_types_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structural_division',
            name='location_map',
            field=models.ImageField(upload_to='ecology/static/ecology/images/location_scheme/', verbose_name='Схема местоположения'),
        ),
        migrations.AlterField(
            model_name='waste_types',
            name='picture',
            field=models.ImageField(upload_to='ecology/static/ecology/images/waste_image/', verbose_name='Картинка отхода'),
        ),
    ]
