# Generated by Django 5.0 on 2024-01-16 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0010_alter_structural_division_location_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danger_class',
            name='code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!'), django.core.validators.MaxLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!')], verbose_name='Код класса опасности'),
        ),
        migrations.AlterField(
            model_name='reason_for_transferring',
            name='code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!'), django.core.validators.MaxLengthValidator(limit_value=2, message='Код д.б. 2-ух значным!')], verbose_name='Код причины'),
        ),
        migrations.AlterField(
            model_name='waste_types',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=7, message='Код д.б. 7-ми значным!'), django.core.validators.MaxLengthValidator(limit_value=7, message='Код д.б. 7-ми значным!')], verbose_name='Код отхода'),
        ),
    ]
