# Generated by Django 5.0 on 2024-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0012_alter_structural_division_location_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officials',
            name='status',
            field=models.BooleanField(choices=[(1, 'Уполномоченный'), (0, 'Не уполномоченный')], default=1, verbose_name='Текущий статус'),
        ),
    ]
