# Generated by Django 5.0 on 2024-01-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0013_alter_officials_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structural_division',
            name='waste_collection',
        ),
        migrations.AddField(
            model_name='waste_collection',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_collection', to='ecology.structural_division', verbose_name='Структурное подразделение'),
        ),
    ]
