# Generated by Django 5.0 on 2024-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0014_remove_structural_division_waste_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structural_division',
            name='rental_area',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь аренды'),
        ),
    ]
