# Generated by Django 5.0 on 2024-01-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0015_alter_structural_division_rental_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_collection',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_collection', to='ecology.structural_division', verbose_name='Структурное подразделение'),
        ),
    ]
