# Generated by Django 5.0 on 2024-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0017_alter_officials_corporate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officials',
            name='corporate_position',
            field=models.CharField(choices=[('Р', 'Руководитель'), ('З', 'Заместитель')], default='Р', max_length=1, verbose_name='Руководитель / Заместитель'),
        ),
    ]
