# Generated by Django 5.0 on 2024-01-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0019_alter_officials_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.CharField(choices=[('Л', 'Легковой автомобль'), ('З', 'Грузовой автомоиль')], max_length=1, verbose_name='Тип автомоиля'),
        ),
    ]
