# Generated by Django 5.0 on 2024-01-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0020_alter_cars_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='prod_year',
            field=models.CharField(max_length=4, verbose_name='Дата производства'),
        ),
    ]
