# Generated by Django 5.0 on 2024-01-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0021_alter_cars_prod_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_data',
            name='for_whom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому передается отход'),
        ),
        migrations.AlterField(
            model_name='waste_data',
            name='position_officials',
            field=models.CharField(max_length=70, verbose_name='Должность ответственного'),
        ),
    ]
